"""flesh out vehicle model

Revision ID: 3552a7590f1b
Revises: 61fbeb990d98
Create Date: 2026-08-04 17:18:48.413216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3552a7590f1b'
down_revision: Union[str, Sequence[str], None] = '61fbeb990d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vehicles_registration_number_key'), 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.create_unique_constraint(op.f('vehicles_registration_number_key'), 'vehicles', ['registration_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
