"""add route_type to trips table

Revision ID: 395f969456b2
Revises: 9b26770e436d
Create Date: 2026-08-10 19:57:30.392598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395f969456b2'
down_revision: Union[str, Sequence[str], None] = '9b26770e436d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('route_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_type')
    # ### end Alembic commands ###
