"""add_fuel_records_columns

Revision ID: 606c10afeddc
Revises: de72887cc1c1
Create Date: 2026-08-14 09:27:31.579720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606c10afeddc'
down_revision: Union[str, Sequence[str], None] = 'de72887cc1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_records', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.add_column('fuel_records', sa.Column('refill_date', sa.String(length=50), nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_type', sa.String(length=50), nullable=True))
    op.add_column('fuel_records', sa.Column('litres', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('price_per_litre', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('total_cost', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('odometer_reading', sa.Float(), nullable=True))
    op.add_column('fuel_records', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('fuel_records', sa.Column('notes', sa.String(length=255), nullable=True))
    op.add_column('fuel_records', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('fuel_records', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'fuel_records', 'drivers', ['driver_id'], ['driver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_records', type_='foreignkey')
    op.alter_column('fuel_records', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('fuel_records', 'created_at')
    op.drop_column('fuel_records', 'notes')
    op.drop_column('fuel_records', 'location')
    op.drop_column('fuel_records', 'odometer_reading')
    op.drop_column('fuel_records', 'total_cost')
    op.drop_column('fuel_records', 'price_per_litre')
    op.drop_column('fuel_records', 'litres')
    op.drop_column('fuel_records', 'fuel_type')
    op.drop_column('fuel_records', 'refill_date')
    op.drop_column('fuel_records', 'driver_id')
    # ### end Alembic commands ###
