"""update vehicle table

Revision ID: 61fbeb990d98
Revises: b1c2d3e4f5a6
Create Date: 2026-08-04 11:12:02.269961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61fbeb990d98'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = postgresql.ENUM('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='roleenum')
    role_enum.create(op.get_bind(), checkfirst=True)

    vehicle_status_enum = postgresql.ENUM('Available', 'Assigned', 'Maintenance', 'In Transit', name='vehicle_status_enum')
    vehicle_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('attendance_user_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'drivers', ['driver_id'], ['driver_id'])
    op.drop_column('attendance', 'date')
    op.drop_column('attendance', 'status')
    op.drop_column('attendance', 'created_at')
    op.drop_column('attendance', 'user_id')
    op.drop_constraint(op.f('drivers_license_number_key'), 'drivers', type_='unique')
    op.drop_column('drivers', 'created_at')
    op.drop_column('drivers', 'license_number')
    op.drop_column('drivers', 'address')
    op.drop_column('drivers', 'experience_years')
    op.drop_column('drivers', 'status')
    op.drop_column('fuel_records', 'fuel_date')
    op.drop_column('fuel_records', 'created_at')
    op.drop_column('fuel_records', 'liters')
    op.drop_column('fuel_records', 'mileage')
    op.drop_column('fuel_records', 'total_cost')
    op.add_column('gps_tracking', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('gps_tracking_trip_id_fkey'), 'gps_tracking', type_='foreignkey')
    op.create_foreign_key(None, 'gps_tracking', 'vehicles', ['vehicle_id'], ['vehicle_id'])
    op.drop_column('gps_tracking', 'trip_id')
    op.drop_column('gps_tracking', 'longitude')
    op.drop_column('gps_tracking', 'speed')
    op.drop_column('gps_tracking', 'latitude')
    op.drop_column('gps_tracking', 'timestamp')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_read')
    op.add_column('shipments', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.add_column('shipments', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'drivers', ['driver_id'], ['driver_id'])
    op.create_foreign_key(None, 'shipments', 'vehicles', ['vehicle_id'], ['vehicle_id'])
    op.drop_column('shipments', 'created_at')
    op.drop_column('shipments', 'sender_name')
    op.drop_column('shipments', 'receiver_name')
    op.drop_column('shipments', 'delivery_location')
    op.drop_column('shipments', 'pickup_location')
    op.drop_column('shipments', 'status')
    op.drop_column('trips', 'end_location')
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'start_location')
    op.drop_column('trips', 'status')
    op.drop_column('trips', 'start_time')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=role_enum,
               postgresql_using='role::roleenum',
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('vehicle_maintenance', 'cost')
    op.drop_column('vehicle_maintenance', 'created_at')
    op.drop_column('vehicle_maintenance', 'description')
    op.drop_column('vehicle_maintenance', 'maintenance_date')
    op.drop_column('vehicle_maintenance', 'status')
    op.add_column('vehicles', sa.Column('registration_number', sa.String(length=30), nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('brand', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('manufacture_year', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(length=30), nullable=False))
    op.add_column('vehicles', sa.Column('assigned_driver_id', sa.UUID(), nullable=True))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('vehicles', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.execute("ALTER TABLE vehicles ALTER COLUMN status DROP DEFAULT;")
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=vehicle_status_enum,
               postgresql_using='status::vehicle_status_enum',
               nullable=False)
    op.execute("ALTER TABLE vehicles ALTER COLUMN status SET DEFAULT 'Available'::vehicle_status_enum;")
    op.drop_constraint(op.f('vehicles_vehicle_number_key'), 'vehicles', type_='unique')
    op.create_unique_constraint(None, 'vehicles', ['registration_number'])
    op.create_foreign_key(None, 'vehicles', 'drivers', ['assigned_driver_id'], ['driver_id'])
    op.drop_column('vehicles', 'vehicle_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    role_enum = postgresql.ENUM('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='roleenum')
    vehicle_status_enum = postgresql.ENUM('Available', 'Assigned', 'Maintenance', 'In Transit', name='vehicle_status_enum')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.create_unique_constraint(op.f('vehicles_vehicle_number_key'), 'vehicles', ['vehicle_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('vehicles', 'status',
               existing_type=vehicle_status_enum,
               type_=sa.VARCHAR(length=20),
               postgresql_using='status::text',
               nullable=True,
               existing_server_default=sa.text("'Available'::character varying"))
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vehicles', 'model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'assigned_driver_id')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'manufacture_year')
    op.drop_column('vehicles', 'brand')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'registration_number')
    op.add_column('vehicle_maintenance', sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('maintenance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=role_enum,
               type_=sa.VARCHAR(length=30),
               postgresql_using='role::text',
               existing_nullable=False)
    op.add_column('trips', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'Scheduled'::character varying"), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('end_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('pickup_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('delivery_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('receiver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'driver_id')
    op.drop_column('shipments', 'vehicle_id')
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gps_tracking', sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gps_tracking', type_='foreignkey')
    op.create_foreign_key(op.f('gps_tracking_trip_id_fkey'), 'gps_tracking', 'trips', ['trip_id'], ['trip_id'])
    op.drop_column('gps_tracking', 'vehicle_id')
    op.add_column('fuel_records', sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('mileage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('drivers_license_number_key'), 'drivers', ['license_number'], postgresql_nulls_not_distinct=False)
    op.add_column('attendance', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Present'::character varying"), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_user_id_fkey'), 'attendance', 'users', ['user_id'], ['user_id'])
    op.drop_column('attendance', 'driver_id')
    # ### end Alembic commands ###
    role_enum.drop(op.get_bind(), checkfirst=True)
    vehicle_status_enum.drop(op.get_bind(), checkfirst=True)

