"""add_license_status_to_drivers_and_maintenance_columns

Revision ID: de72887cc1c1
Revises: 395f969456b2
Create Date: 2026-08-13 21:34:52.109278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de72887cc1c1'
down_revision: Union[str, Sequence[str], None] = '395f969456b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('drivers', sa.Column('license_expiry', sa.String(length=30), nullable=True))
    op.add_column('drivers', sa.Column('status', sa.String(length=30), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('maintenance_type', sa.String(length=100), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('scheduled_date', sa.String(length=50), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('status', sa.String(length=30), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_maintenance', 'created_at')
    op.drop_column('vehicle_maintenance', 'status')
    op.drop_column('vehicle_maintenance', 'cost')
    op.drop_column('vehicle_maintenance', 'description')
    op.drop_column('vehicle_maintenance', 'scheduled_date')
    op.drop_column('vehicle_maintenance', 'maintenance_type')
    op.drop_column('drivers', 'status')
    op.drop_column('drivers', 'license_expiry')
    op.drop_column('drivers', 'license_number')
    # ### end Alembic commands ###
